# Docker Compose Override para Desenvolvimento
# Este arquivo é automaticamente carregado pelo docker-compose
# e sobrescreve configurações do docker-compose.yml principal

version: '3.8'

services:
  postgres:
    # Configurações específicas para desenvolvimento
    environment:
      # Logs mais verbosos para debug
      POSTGRES_LOG_STATEMENT: "all"
      POSTGRES_LOG_MIN_DURATION_STATEMENT: 1000
    # Expor portas adicionais se necessário
    ports:
      - "5432:5432"
    # Volumes para persistir dados de desenvolvimento
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    # Configurações de performance para desenvolvimento
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c track_activity_query_size=2048
      -c pg_stat_statements.track=all
      -c log_statement=mod
      -c log_min_duration_statement=1000
      -c log_line_prefix='%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '

  redis:
    # Configurações específicas para desenvolvimento
    environment:
      # Logs mais verbosos
      REDIS_LOG_LEVEL: "verbose"
    # Comandos adicionais para desenvolvimento
    command: >
      redis-server
      --appendonly yes
      --requirepass barbersaas123
      --loglevel verbose
      --logfile /var/log/redis/redis.log

  pgadmin:
    # Configurações específicas para desenvolvimento
    environment:
      # Desabilitar verificação de email
      PGADMIN_CONFIG_MAIL_SERVER: ""
      PGADMIN_CONFIG_MAIL_PORT: 0
      PGADMIN_CONFIG_MAIL_USE_TLS: false
      PGADMIN_CONFIG_MAIL_USE_SSL: false
      # Configurações de debug
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "DEBUG"
    # Volumes para persistir configurações
    volumes:
      - pgadmin_dev_data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json:ro

volumes:
  postgres_dev_data:
    driver: local
  pgadmin_dev_data:
    driver: local
